### ISSUE TITLE
Can't apply pagination and Vue Infinity Loading

### ISSUE THREAD

**Issue by arepson** [noxify/gridsome-starter-liebling#1]
I'm try add indeks post with pagination and vue infinity loading, can you help how to use in this template?

**Comment by noxify** [comment]
Hi @arepson 

* Could you explain what isn’t working? 
* Which errors are shown? 
* Do you have an example repo? 

Thanks!

Regards,
Marcus

**Comment by noxify** [comment]
@arepson - i have created an example based on https://gridsome.org/blog/2019/10/08/infinite-loading-with-gridsome/ .

I have tested it with `gridsome develop` and `gridsome build`.

Online example: https://gridsome-starter-liebling.now.sh/infinity

Hope that helps.

**Comment by arepson** [comment]
Thanks:) It's work now
