### ISSUE TITLE
Kindly add support for headless cms

### ISSUE THREAD

**Issue by stephenajulu** [noxify/gridsome-starter-liebling#2]
Hi, how are you?
Kindly add support for headless cms like Netlify or Forestry.
This will really help me.
Or if you can kindly show me how to add it to my own.
This theme is great been waiting for it to be ported to JAMstack, now all i need is a CMS.

**Comment by noxify** [comment]
Hi @stephenajulu ,

thanks for the feedback.

With https://github.com/gridsome/gridsome/pull/806 we can deliver different graphql queries for each data source.

But currently, you have to replace the existing graphQL queries manually.

Hope that helps :)

I close this currently - If I missed something, feel free to re-open the issue.

Thanks & Regards,
Marcus
